### ISSUE TITLE
Not Copying In Sketch 41

### ISSUE THREAD

**Issue by brandonkboswell** [graphical-iain/Copy-SCSS-Colors#1]
I recently installed the plugin into Sketch 41, Selected all of the Objects in my page and then ran the plugin but my clipboard does not populate. Perhaps I'm doing something wrong, but I figured I would bring this up.

**Comment by graphical-iain** [comment]
I'll take a look. I originally wrote this plugin for an older version of sketch, so there might be compatibility issues.

**Comment by graphical-iain** [comment]
@brandonkboswell it appears that the function I am using to convert the fill color to a css hex color has been removed from sketch. I've submitted an issue with the Sketch API team. I'll let you know if I hear anything.

**Comment by graphical-iain** [comment]
Plugin has been updated and is working correctly again. 
Cause of the issue: http://sketchplugins.com/d/9-api-to-get-backgroundcolor
